"""Sanity tests for the public JSON Schema 2020-12 contracts in
``docs/schemas/``.

The schemas are the public interop surface (see ``docs/schemas/README.md``).
They are NOT the canonical implementation — Python dataclasses and the
Python verifiers are — but they must stay aligned. These tests catch
drift in two directions:

1. Every schema is itself a valid Draft 2020-12 metaschema (no typos in
   keywords, refs resolve).
2. Representative fixtures generated by the canonical implementation
   validate cleanly against their schema. If the implementation adds a
   field or tightens a value, the schema must be updated in lockstep or
   this test fails.

We deliberately do NOT add a generic property-based test ("any output of
the implementation must validate against the schema") because the
schemas are structural-only — semantic invariants (DAG acyclicity, chain
linkage, etc.) live in the verifiers, not the schema, by design.
"""

from __future__ import annotations

import datetime as dt
import json
from collections.abc import Callable
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator

from aip import Archive
from aip.attestation import generate_keypair, serialize_public_key_pem
from aip.audit import log as audit_log
from aip.core.evidence import EvidenceKind
from aip.core.source import AuthorityLevel, SourceKind
from aip.transparency.key_declaration import (
    WitnessSeed,
    init_declaration,
    operator_public_key_path,
)
from aip.transparency.store import TRANSPARENCY_DIRNAME

REPO_ROOT = Path(__file__).resolve().parents[3]
SCHEMA_DIR = REPO_ROOT / "docs" / "schemas"
KEY_DECLARATION_SCHEMA = SCHEMA_DIR / "key-declaration.v1.schema.json"
INFERENCE_PROOF_SCHEMA = SCHEMA_DIR / "inference-proof.v1.schema.json"
AUDIT_ENTRY_SCHEMA = SCHEMA_DIR / "audit-entry.v1.schema.json"
TRANSPARENCY_MANIFEST_SCHEMA = SCHEMA_DIR / "transparency-manifest.v1.schema.json"
CAPTURE_CERT_SCHEMA = SCHEMA_DIR / "capture-certificate.v1.schema.json"
WITNESS_ATTESTATION_SCHEMA = SCHEMA_DIR / "witness-attestation.v1.schema.json"

UTC = dt.UTC
CANONICAL_TS = dt.datetime(2026, 6, 10, 0, 0, 0, tzinfo=UTC)


def _load_schema(path: Path) -> dict[str, object]:
    data: dict[str, object] = json.loads(path.read_text(encoding="utf-8"))
    return data


def _fixed_clock(ts: dt.datetime) -> Callable[[], dt.datetime]:
    return lambda: ts


# --------------------------------------------------------------- meta


def test_all_schemas_are_valid_draft_2020_12_metaschemas() -> None:
    """Each schema file in docs/schemas/ must itself be a valid Draft 2020-12
    schema. Catches typos in keywords ('require' vs 'required', '$Ref' vs
    '$ref') that would silently allow anything to validate."""
    for path in sorted(SCHEMA_DIR.glob("*.schema.json")):
        schema = _load_schema(path)
        # Draft202012Validator.check_schema raises if the schema is malformed.
        Draft202012Validator.check_schema(schema)


def test_every_schema_has_id_and_schema_keywords() -> None:
    """Hard requirement for stable interop: each schema must declare both
    '$schema' (so validators know which draft) and '$id' (so external
    consumers can pin to a stable URL even before publication)."""
    for path in sorted(SCHEMA_DIR.glob("*.schema.json")):
        schema = _load_schema(path)
        assert schema.get("$schema") == (
            "https://json-schema.org/draft/2020-12/schema"
        ), f"{path.name} missing or wrong $schema"
        sid = schema.get("$id", "")
        assert isinstance(sid, str) and sid.startswith("https://"), (
            f"{path.name} missing or non-URL $id"
        )


# --------------------------------------------------------------- key declaration


def test_minimal_key_declaration_validates(archive_root: Path) -> None:
    """The minimum-shaped declaration produced by ``init_declaration`` is the
    same one the receptor sees in the report. It must validate."""
    # Seed an operator pubkey on disk so init can compute the fingerprint.
    _, pub = generate_keypair()
    pem = serialize_public_key_pem(pub)
    (archive_root / TRANSPARENCY_DIRNAME).mkdir(parents=True)
    operator_public_key_path(archive_root).write_bytes(pem)

    decl = init_declaration(archive_root, operator_id="op-x")
    schema = _load_schema(KEY_DECLARATION_SCHEMA)
    Draft202012Validator(schema).validate(decl)


def test_key_declaration_with_witnesses_validates(
    archive_root: Path,
) -> None:
    _, pub = generate_keypair()
    (archive_root / TRANSPARENCY_DIRNAME).mkdir(parents=True)
    operator_public_key_path(archive_root).write_bytes(
        serialize_public_key_pem(pub)
    )

    decl = init_declaration(
        archive_root,
        operator_id="op-x",
        first_published_at="2026-06-01T00:00:00Z",
        witnesses=(WitnessSeed("alice", "a" * 64), WitnessSeed("bob", "b" * 64)),
    )
    # Add a reference manually so the witness block has all the fields the
    # schema describes (not just the empty external_references list).
    decl["witnesses"][0]["external_references"].append(
        {"kind": "https_pem", "uri": "https://alice.example/k.pem", "note": "n"}
    )
    schema = _load_schema(KEY_DECLARATION_SCHEMA)
    Draft202012Validator(schema).validate(decl)


def test_key_declaration_rejects_wrong_discriminator() -> None:
    schema = _load_schema(KEY_DECLARATION_SCHEMA)
    bad = {
        "declaration_type": "fake.type.v1",
        "schema_version": "1",
        "operator": {
            "operator_id": "x",
            "public_key_fingerprint": "a" * 64,
            "external_references": [],
        },
    }
    with pytest.raises(Exception, match=r"aip\.transparency\.key-declaration\.v1"):
        Draft202012Validator(schema).validate(bad)


def test_key_declaration_rejects_invalid_fingerprint() -> None:
    schema = _load_schema(KEY_DECLARATION_SCHEMA)
    bad = {
        "declaration_type": "aip.transparency.key-declaration.v1",
        "schema_version": "1",
        "operator": {
            "operator_id": "x",
            "public_key_fingerprint": "not-hex",
            "external_references": [],
        },
    }
    with pytest.raises(Exception):  # noqa: B017 — message variability across versions
        Draft202012Validator(schema).validate(bad)


def test_key_declaration_rejects_external_ref_without_uri() -> None:
    schema = _load_schema(KEY_DECLARATION_SCHEMA)
    bad = {
        "declaration_type": "aip.transparency.key-declaration.v1",
        "schema_version": "1",
        "operator": {
            "operator_id": "x",
            "public_key_fingerprint": "a" * 64,
            "external_references": [{"kind": "https_pem"}],  # missing uri
        },
    }
    with pytest.raises(Exception, match="uri"):
        Draft202012Validator(schema).validate(bad)


# --------------------------------------------------------------- inference proof


_PROOF_FIXTURE_PATH = REPO_ROOT / "tmp" / "integration-test" / "archive" / (
    "inference-proofs"
) / "uap-001-anomaly-v1.json"


def test_inference_proof_fixture_validates() -> None:
    """The canonical Phase-5 fixture must validate. It is the same proof
    that ships through the integration tests, the demo path, and the
    TypeScript test fixtures — if any of those bend the shape, this
    test will catch the drift first."""
    if not _PROOF_FIXTURE_PATH.is_file():
        pytest.skip("integration-test fixture absent in this checkout")
    proof = json.loads(_PROOF_FIXTURE_PATH.read_text(encoding="utf-8"))
    schema = _load_schema(INFERENCE_PROOF_SCHEMA)
    Draft202012Validator(schema).validate(proof)


def test_inference_proof_rejects_unknown_rule() -> None:
    schema = _load_schema(INFERENCE_PROOF_SCHEMA)
    bad = {
        "proof_type": "aip.justification.inference-proof.v1",
        "schema_version": "1",
        "proof_id": "p-1",
        "target_justification_id": "j-1",
        "target_justification_hash": "f" * 64,
        "premises": [
            {"id": "P1", "text": "t", "evidence_refs": [], "kind": "observation"}
        ],
        "inferences": [
            {
                "id": "I1",
                "rule": "wishful_thinking",  # not in closed vocabulary
                "input_claim_ids": ["P1"],
                "output_claim_id": "C1",
                "text": "t",
            }
        ],
        "derived_claims": [{"id": "C1", "text": "t", "inferred_by": "I1"}],
        "conclusion_claim_id": "C1",
        "proof_hash": "a" * 64,
    }
    with pytest.raises(Exception, match=r"wishful_thinking|enum"):
        Draft202012Validator(schema).validate(bad)


def test_inference_proof_rejects_invalid_id_characters() -> None:
    schema = _load_schema(INFERENCE_PROOF_SCHEMA)
    bad = {
        "proof_type": "aip.justification.inference-proof.v1",
        "schema_version": "1",
        "proof_id": "p 1 with spaces",  # invalid per id pattern
        "target_justification_id": "j-1",
        "target_justification_hash": "f" * 64,
        "premises": [],
        "inferences": [],
        "derived_claims": [],
        "conclusion_claim_id": "P1",
        "proof_hash": "a" * 64,
    }
    with pytest.raises(Exception):  # noqa: B017
        Draft202012Validator(schema).validate(bad)


def test_inference_proof_rejects_unknown_premise_kind() -> None:
    schema = _load_schema(INFERENCE_PROOF_SCHEMA)
    bad = {
        "proof_type": "aip.justification.inference-proof.v1",
        "schema_version": "1",
        "proof_id": "p-1",
        "target_justification_id": "j-1",
        "target_justification_hash": "f" * 64,
        "premises": [
            {"id": "P1", "text": "t", "evidence_refs": [], "kind": "hearsay"}
        ],
        "inferences": [],
        "derived_claims": [],
        "conclusion_claim_id": "P1",
        "proof_hash": "a" * 64,
    }
    with pytest.raises(Exception, match=r"hearsay|enum"):
        Draft202012Validator(schema).validate(bad)


# --------------------------------------------------------------- audit entry


def _ingest(archive_root: Path, blob_path: Path) -> str:
    archive = Archive.open(archive_root)
    ev = archive.ingest_evidence(
        blob_path,
        source_id="schema-test-src",
        source_name="Schema Test Source",
        source_kind=SourceKind.GOVERNMENT_ARCHIVE,
        source_authority=AuthorityLevel.SECONDARY,
        source_jurisdiction="US",
        source_license="public_domain",
        evidence_kind=EvidenceKind.DOCUMENT_SCAN,
        mime_type="application/pdf",
        ingested_by="@schema-test",
        clock=_fixed_clock(CANONICAL_TS),
    )
    return ev.hash


def test_real_audit_entries_validate(
    tmp_path: Path, archive_root: Path
) -> None:
    """End-to-end: ingest one evidence, walk the audit log, validate every
    entry against the schema. Bootstrap entries and ingest entries are
    the two shapes we ship today."""
    blob = tmp_path / "doc.pdf"
    blob.write_bytes(b"%PDF-1.4 schema-test-blob")
    _ingest(archive_root, blob)

    schema = _load_schema(AUDIT_ENTRY_SCHEMA)
    validator = Draft202012Validator(schema)

    for entry in audit_log.iter_entries(archive_root):
        # iter_entries hands back a pydantic model; serialise to the
        # canonical wire dict before validating.
        as_wire = entry.to_canonical_dict()
        validator.validate(as_wire)


def test_audit_entry_rejects_unknown_action() -> None:
    schema = _load_schema(AUDIT_ENTRY_SCHEMA)
    bad = {
        "seq": 0,
        "prev_hash": "0" * 64,
        "timestamp": "2026-06-10T00:00:00Z",
        "actor": "@x",
        "action": "delete_archive",  # not in vocabulary
        "target": "aip:archive/bootstrap",
        "parameters": {},
        "result": "success",
        "schema_version": "0.1.0",
        "entry_hash": "a" * 64,
    }
    with pytest.raises(Exception, match=r"delete_archive|enum"):
        Draft202012Validator(schema).validate(bad)


def test_audit_entry_rejects_subsecond_timestamp() -> None:
    schema = _load_schema(AUDIT_ENTRY_SCHEMA)
    bad = {
        "seq": 0,
        "prev_hash": "0" * 64,
        "timestamp": "2026-06-10T00:00:00.123Z",  # subsecond not allowed (ADR-0024 L2)
        "actor": "@x",
        "action": "archive_bootstrap",
        "target": "aip:archive/bootstrap",
        "parameters": {},
        "result": "success",
        "schema_version": "0.1.0",
        "entry_hash": "a" * 64,
    }
    with pytest.raises(Exception, match=r"timestamp|pattern"):
        Draft202012Validator(schema).validate(bad)


def test_audit_entry_rejects_extra_top_level_field() -> None:
    schema = _load_schema(AUDIT_ENTRY_SCHEMA)
    bad = {
        "seq": 0,
        "prev_hash": "0" * 64,
        "timestamp": "2026-06-10T00:00:00Z",
        "actor": "@x",
        "action": "archive_bootstrap",
        "target": "aip:archive/bootstrap",
        "parameters": {},
        "result": "success",
        "schema_version": "0.1.0",
        "entry_hash": "a" * 64,
        "extra_field": "should not be here",
    }
    with pytest.raises(Exception, match=r"extra_field|additional"):
        Draft202012Validator(schema).validate(bad)


# --------------------------------------------------------------- transparency manifest


_DEMO_MANIFEST_PATH = REPO_ROOT / "docs" / "demo" / "demo_archive" / (
    "transparency"
) / "manifest-000000.json"


def test_demo_transparency_manifest_validates() -> None:
    """The signed demo manifest is the same shape every other archive
    publishes. Validating it here pins the public contract of
    ``aip transparency publish``."""
    if not _DEMO_MANIFEST_PATH.is_file():
        pytest.skip("demo manifest absent in this checkout")
    manifest = json.loads(_DEMO_MANIFEST_PATH.read_text(encoding="utf-8"))
    schema = _load_schema(TRANSPARENCY_MANIFEST_SCHEMA)
    Draft202012Validator(schema).validate(manifest)


def test_transparency_manifest_rejects_invalid_signature_length() -> None:
    schema = _load_schema(TRANSPARENCY_MANIFEST_SCHEMA)
    bad = {
        "manifest_type": "aip.transparency.manifest.v1",
        "schema_version": "1",
        "sequence": 0,
        "operator_id": "op-x",
        "signed_at": "2026-06-10T00:00:00Z",
        "previous_manifest_hash": "0" * 64,
        "audit_chain_head_hash": "a" * 64,
        "archive_manifest_hash": "a" * 64,
        "audit_entry_count": 0,
        "evidence_count": 0,
        "attestation_count": 0,
        "justification_count": 0,
        "snapshot_count": 0,
        "timeline_count": 0,
        "workspace_count": 0,
        "public_key_fingerprint": "a" * 64,
        "signature_algorithm": "ed25519-v1",
        "signature": "ab",  # not 128 hex chars
        "manifest_hash": "a" * 64,
    }
    with pytest.raises(Exception, match=r"signature|pattern"):
        Draft202012Validator(schema).validate(bad)


def test_transparency_manifest_rejects_negative_counts() -> None:
    schema = _load_schema(TRANSPARENCY_MANIFEST_SCHEMA)
    bad = {
        "manifest_type": "aip.transparency.manifest.v1",
        "schema_version": "1",
        "sequence": 0,
        "operator_id": "op-x",
        "signed_at": "2026-06-10T00:00:00Z",
        "previous_manifest_hash": "0" * 64,
        "audit_chain_head_hash": "a" * 64,
        "archive_manifest_hash": "a" * 64,
        "audit_entry_count": -1,  # negative → invalid
        "evidence_count": 0,
        "attestation_count": 0,
        "justification_count": 0,
        "snapshot_count": 0,
        "timeline_count": 0,
        "workspace_count": 0,
        "public_key_fingerprint": "a" * 64,
        "signature_algorithm": "ed25519-v1",
        "signature": "a" * 128,
        "manifest_hash": "a" * 64,
    }
    with pytest.raises(Exception, match=r"audit_entry_count|minimum"):
        Draft202012Validator(schema).validate(bad)


# --------------------------------------------------------------- capture certificate


_CAPTURE_CERT_FIXTURE = REPO_ROOT / "tmp" / "integration-test" / "sample.cert.json"


def test_capture_certificate_fixture_validates() -> None:
    if not _CAPTURE_CERT_FIXTURE.is_file():
        pytest.skip("capture cert fixture absent in this checkout")
    cert = json.loads(_CAPTURE_CERT_FIXTURE.read_text(encoding="utf-8"))
    schema = _load_schema(CAPTURE_CERT_SCHEMA)
    Draft202012Validator(schema).validate(cert)


def test_capture_certificate_accepts_minimal_required_shape() -> None:
    schema = _load_schema(CAPTURE_CERT_SCHEMA)
    minimal = {
        "certificate_type": "aip.capture.certificate.v1",
        "schema_version": "1",
        "evidence_sha256": "a" * 64,
        "captured_at": "2026-06-10T00:00:00Z",
        "device_id": "cam-1",
        "operator_id": "op-x",
        "public_key_fingerprint": "b" * 64,
        "signature_algorithm": "ed25519-v1",
        "signature": "c" * 128,
        "certificate_hash": "d" * 64,
    }
    Draft202012Validator(schema).validate(minimal)


def test_capture_certificate_rejects_invalid_evidence_hash() -> None:
    schema = _load_schema(CAPTURE_CERT_SCHEMA)
    bad = {
        "certificate_type": "aip.capture.certificate.v1",
        "schema_version": "1",
        "evidence_sha256": "ABCD",  # uppercase + too short
        "captured_at": "2026-06-10T00:00:00Z",
        "device_id": "cam-1",
        "operator_id": "op-x",
        "public_key_fingerprint": "b" * 64,
        "signature_algorithm": "ed25519-v1",
        "signature": "c" * 128,
        "certificate_hash": "d" * 64,
    }
    with pytest.raises(Exception, match=r"evidence_sha256|pattern"):
        Draft202012Validator(schema).validate(bad)


# --------------------------------------------------------------- witness attestation


def _find_witness_fixture() -> Path | None:
    """Locate any witness attestation .json in the repo's dev_archive.

    Returns the first match, or None if none are present."""
    base = REPO_ROOT / "dev_archive" / "transparency" / "witnesses"
    if not base.is_dir():
        return None
    for p in base.rglob("*.json"):
        return p
    return None


def test_witness_attestation_fixture_validates() -> None:
    fixture = _find_witness_fixture()
    if fixture is None:
        pytest.skip("no witness attestation fixture in this checkout")
    attestation = json.loads(fixture.read_text(encoding="utf-8"))
    schema = _load_schema(WITNESS_ATTESTATION_SCHEMA)
    Draft202012Validator(schema).validate(attestation)


def test_witness_attestation_accepts_minimal_required_shape() -> None:
    schema = _load_schema(WITNESS_ATTESTATION_SCHEMA)
    minimal = {
        "attestation_type": "aip.transparency.witness.v1",
        "schema_version": "1",
        "witness_operator_id": "w-1",
        "witness_public_key_fingerprint": "a" * 64,
        "target_operator_id": "op-x",
        "target_manifest_sequence": 0,
        "target_manifest_hash": "b" * 64,
        "witnessed_at": "2026-06-10T00:00:00Z",
        "statement": "verified independently",
        "signature_algorithm": "ed25519-v1",
        "signature": "c" * 128,
        "attestation_hash": "d" * 64,
    }
    Draft202012Validator(schema).validate(minimal)


def test_witness_attestation_rejects_empty_statement() -> None:
    """A witness who signs an empty statement is signing nothing — the
    schema's minLength prevents that footgun."""
    schema = _load_schema(WITNESS_ATTESTATION_SCHEMA)
    bad = {
        "attestation_type": "aip.transparency.witness.v1",
        "schema_version": "1",
        "witness_operator_id": "w-1",
        "witness_public_key_fingerprint": "a" * 64,
        "target_operator_id": "op-x",
        "target_manifest_sequence": 0,
        "target_manifest_hash": "b" * 64,
        "witnessed_at": "2026-06-10T00:00:00Z",
        "statement": "",
        "signature_algorithm": "ed25519-v1",
        "signature": "c" * 128,
        "attestation_hash": "d" * 64,
    }
    with pytest.raises(Exception, match=r"statement|minLength"):
        Draft202012Validator(schema).validate(bad)


def test_witness_attestation_rejects_wrong_signature_algorithm() -> None:
    """v1 schema pins signature_algorithm to ed25519-v1. Any other value
    means the artifact belongs to a future schema version, not v1."""
    schema = _load_schema(WITNESS_ATTESTATION_SCHEMA)
    bad = {
        "attestation_type": "aip.transparency.witness.v1",
        "schema_version": "1",
        "witness_operator_id": "w-1",
        "witness_public_key_fingerprint": "a" * 64,
        "target_operator_id": "op-x",
        "target_manifest_sequence": 0,
        "target_manifest_hash": "b" * 64,
        "witnessed_at": "2026-06-10T00:00:00Z",
        "statement": "ok",
        "signature_algorithm": "rsa-v1",  # not allowed in v1
        "signature": "c" * 128,
        "attestation_hash": "d" * 64,
    }
    with pytest.raises(Exception, match=r"signature_algorithm|ed25519-v1|const"):
        Draft202012Validator(schema).validate(bad)
